# Exported from Render on 2024-06-22T12:04:13Z
databases:
- name: gps-data
  databaseName: interviews_kzt8
  user: admin
  plan: starter
  region: singapore
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
services:
- type: web
  name: gps-test
  runtime: python
  repo: https://github.com/anilsrik/gps-test
  plan: free
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: PORT
    sync: false
  region: singapore
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port 80 --log-config=log_conf.yaml
  autoDeploy: false
version: "1"
